/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.ControleCarro;
import java.awt.Component;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author fabricioguidine
 */
public class TelaNovoCarro extends javax.swing.JFrame {
    
    JFrame TelaAnterior;
    ControleCarro novoCarro;
    Locale localeBR = new Locale("pt", "BR");
    NumberFormat dinheiro = NumberFormat.getCurrencyInstance(localeBR);
    private Object campoModelo;
    
    /**
     * Creates new form novoCarro
     */
    private TelaNovoCarro() {
        initComponents();
    }
    
    public TelaNovoCarro(JFrame TelaAnterior){
        this();
        this.TelaAnterior = TelaAnterior;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelModelo = new javax.swing.JLabel();
        labelMarca = new javax.swing.JLabel();
        labelAno = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        try{
            campoAno = new JFormattedTextField(new MaskFormatter("####"))
            ;
            separadorAno = new javax.swing.JSeparator();
            campoMarca = new javax.swing.JTextField();
            separadorMarca = new javax.swing.JSeparator();
            campoValor = new javax.swing.JTextField();
            separadorValor = new javax.swing.JSeparator();
            labelSalvar = new javax.swing.JLabel();
            botaoSalvar = new javax.swing.JButton();
            labelCancelar = new javax.swing.JLabel();
            botaoCancelar = new javax.swing.JButton();
            javax.swing.JComboBox<String> campoModelo = new javax.swing.JComboBox<>();
            labelFundo = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            labelModelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            labelModelo.setForeground(new java.awt.Color(204, 204, 204));
            labelModelo.setText("Modelo");
            getContentPane().add(labelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

            labelMarca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            labelMarca.setForeground(new java.awt.Color(204, 204, 204));
            labelMarca.setText("Marca");
            getContentPane().add(labelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

            labelAno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            labelAno.setForeground(new java.awt.Color(204, 204, 204));
            labelAno.setText("Ano");
            getContentPane().add(labelAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

            labelValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            labelValor.setForeground(new java.awt.Color(204, 204, 204));
            labelValor.setText("Valor");
            getContentPane().add(labelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        }catch(ParseException e){}
        campoAno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoAno.setForeground(new java.awt.Color(204, 204, 204));
        campoAno.setText("Insira o ano...");
        campoAno.setBorder(null);
        campoAno.setOpaque(false);
        campoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAnoActionPerformed(evt);
            }
        });
        getContentPane().add(campoAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 164, 30));
        getContentPane().add(separadorAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 170, 20));

        campoMarca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoMarca.setForeground(new java.awt.Color(204, 204, 204));
        campoMarca.setText("Insira a marca...");
        campoMarca.setBorder(null);
        campoMarca.setOpaque(false);
        campoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(campoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, 30));
        getContentPane().add(separadorMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 30));

        campoValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoValor.setForeground(new java.awt.Color(204, 204, 204));
        campoValor.setText("Insira o valor...");
        campoValor.setBorder(null);
        campoValor.setOpaque(false);
        campoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorActionPerformed(evt);
            }
        });
        getContentPane().add(campoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 164, 30));
        getContentPane().add(separadorValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 170, 30));

        labelSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelSalvar.setText("Salvar");
        getContentPane().add(labelSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/entrar.png"))); // NOI18N
        botaoSalvar.setBorder(null);
        botaoSalvar.setBorderPainted(false);
        botaoSalvar.setContentAreaFilled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        labelCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCancelar.setText("Cancelar");
        getContentPane().add(labelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, 20));

        botaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/entrar.png"))); // NOI18N
        botaoCancelar.setBorder(null);
        botaoCancelar.setOpaque(false);
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 340, 80));
        getContentPane().add(campoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, 30));

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/fundo2.png"))); // NOI18N
        getContentPane().add(labelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAnoActionPerformed

    private void campoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMarcaActionPerformed

    private void campoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:
        
        String marca = this.campoMarca.getText();
        String modelo;
        modelo = this.campoModelo.getSelectedItem().toString();
        String ano = this.campoAno.getText();
        float valor;
        try{
        valor = Float.parseFloat(this.campoValor.getText());
        }catch(Exception e){
            valor = -1;
        }
        novoCarro = new ControleCarro(marca, modelo, ano, valor);
        novoCarro.verificaInfo();
        if(novoCarro.getErros().size() > 0){
            int i = 0;
            JOptionPane.showMessageDialog(null, novoCarro.getErros().get(i));
        }
        else{
            JButton editar  = new javax.swing.JButton();
            
            editar.addActionListener(this.botaoCancelar.getAction());
            
            
            JOptionPane verifica = new JOptionPane();
            verifica.showConfirmDialog(null, "Marca: " + marca + "\nModelo: " + modelo + "\nAno: " + ano + "\nValor: " + dinheiro.format(valor));
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        // TODO add your handling code here:
        TelaAnterior.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoMarca;
    private javax.swing.JTextField campoValor;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelCancelar;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelSalvar;
    private javax.swing.JLabel labelValor;
    private javax.swing.JSeparator separadorAno;
    private javax.swing.JSeparator separadorMarca;
    private javax.swing.JSeparator separadorValor;
    // End of variables declaration//GEN-END:variables
}
